// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSbG1L8PCG-W2VG1cmeBeTxV2Z203pKo',
    appId: '1:259680947834:android:f0770c8edf47997f52b5c3',
    messagingSenderId: '259680947834',
    projectId: 'tracking-app-8cf65',
    storageBucket: 'tracking-app-8cf65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vz0rQ90il0q9vWFnBvJg-SXgnQlJcsI',
    appId: '1:259680947834:ios:91d7518288dc808052b5c3',
    messagingSenderId: '259680947834',
    projectId: 'tracking-app-8cf65',
    storageBucket: 'tracking-app-8cf65.firebasestorage.app',
    iosBundleId: 'com.example.aiTrackingApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ97zmhuZ-j_0zH1VBmLzW_ZbKdMTj214',
    appId: '1:259680947834:web:5a2296649603addc52b5c3',
    messagingSenderId: '259680947834',
    projectId: 'tracking-app-8cf65',
    authDomain: 'tracking-app-8cf65.firebaseapp.com',
    storageBucket: 'tracking-app-8cf65.firebasestorage.app',
    measurementId: 'G-9MVV69P7BC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3vz0rQ90il0q9vWFnBvJg-SXgnQlJcsI',
    appId: '1:259680947834:ios:91d7518288dc808052b5c3',
    messagingSenderId: '259680947834',
    projectId: 'tracking-app-8cf65',
    storageBucket: 'tracking-app-8cf65.firebasestorage.app',
    iosBundleId: 'com.example.aiTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ97zmhuZ-j_0zH1VBmLzW_ZbKdMTj214',
    appId: '1:259680947834:web:589c0fd7c5e4f73852b5c3',
    messagingSenderId: '259680947834',
    projectId: 'tracking-app-8cf65',
    authDomain: 'tracking-app-8cf65.firebaseapp.com',
    storageBucket: 'tracking-app-8cf65.firebasestorage.app',
    measurementId: 'G-Q69Z5NTRSB',
  );

}